import type { Area } from '@/types/record'
import type { Sign } from '@/types/workspace'

export type CadenceKey = 'monthly' | 'bimonthly' | 'quarterly' | 'semestral' | 'annual'

export const CADENCE_OPTIONS: { value: CadenceKey; label: string; intervalMonths: number }[] = [
  { value: 'monthly', label: 'Mensile', intervalMonths: 1 },
  { value: 'bimonthly', label: 'Bimestrale', intervalMonths: 2 },
  { value: 'quarterly', label: 'Trimestrale', intervalMonths: 3 },
  { value: 'semestral', label: 'Semestrale', intervalMonths: 6 },
  { value: 'annual', label: 'Annuale', intervalMonths: 12 },
]

export const CADENCE_LABELS: Record<CadenceKey, string> = Object.fromEntries(
  CADENCE_OPTIONS.map((o) => [o.value, o.label]),
) as Record<CadenceKey, string>

export const CADENCE_MONTHS: Record<CadenceKey, number> = Object.fromEntries(
  CADENCE_OPTIONS.map((o) => [o.value, o.intervalMonths]),
) as Record<CadenceKey, number>

export const HORIZON_OPTIONS = [12, 24, 36, 60] as const

export interface OnboardingPreset {
  id: string
  label: string
  hint?: string
  accountSuggestion: string
  type: string
  sign: Sign
  defaultArea: Area
  defaultCadence: CadenceKey
  defaultVatRate: number
  defaultWithholdingRate: number
  defaultVatDeduction: number
  defaultHorizonMonths: number
  defaultStage: string
  defaultEnabled: boolean
}

export const COST_PRESETS: OnboardingPreset[] = [
  {
    id: 'affitto-immobile',
    label: 'Affitto immobile',
    hint: 'Canone mensile di locazione (uffici, magazzini, negozi). Aggiungi una riga per ogni immobile.',
    accountSuggestion: 'AFFITTO IMMOBILE',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 0,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 24,
    defaultStage: '0',
    defaultEnabled: true,
  },
  {
    id: 'utenze-elettriche',
    label: 'Utenze elettriche',
    hint: 'Bollette energia elettrica. Tipicamente bimestrali.',
    accountSuggestion: 'UTENZE ELETTRICHE',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'bimonthly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 24,
    defaultStage: '0',
    defaultEnabled: true,
  },
  {
    id: 'utenze-gas-acqua',
    label: 'Utenze gas e acqua',
    hint: 'Bollette gas, acqua, riscaldamento.',
    accountSuggestion: 'UTENZE GAS ACQUA',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'bimonthly',
    defaultVatRate: 10,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 24,
    defaultStage: '0',
    defaultEnabled: true,
  },
  {
    id: 'telefonia-internet',
    label: 'Telefonia e internet',
    hint: 'Connettività dati, telefonia fissa e mobile. Deducibilità IVA tipicamente al 50% per telefonia mobile.',
    accountSuggestion: 'TELEFONIA INTERNET',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 24,
    defaultStage: '0',
    defaultEnabled: true,
  },
  {
    id: 'commercialista',
    label: 'Commercialista',
    hint: 'Compenso periodico al commercialista. Ritenuta d’acconto 20% di norma.',
    accountSuggestion: 'COMMERCIALISTA',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'quarterly',
    defaultVatRate: 22,
    defaultWithholdingRate: 20,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 24,
    defaultStage: '0',
    defaultEnabled: true,
  },
  {
    id: 'consulenze-varie',
    label: 'Consulenze varie',
    hint: 'Consulenze legali, IT, marketing ricorrenti. Imposta ritenuta 20% se professionisti.',
    accountSuggestion: 'CONSULENZE',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 22,
    defaultWithholdingRate: 20,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 12,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'abbonamenti-saas',
    label: 'Abbonamenti SaaS / software',
    hint: 'Software cloud (Google Workspace, Microsoft 365, gestionali, hosting). Cadenza mensile o annuale.',
    accountSuggestion: 'SOFTWARE SAAS',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 12,
    defaultStage: '0',
    defaultEnabled: true,
  },
  {
    id: 'leasing-automezzi',
    label: 'Leasing automezzi',
    hint: 'Canoni leasing auto/furgoni. Deducibilità IVA tipicamente al 40% per auto aziendali.',
    accountSuggestion: 'LEASING AUTO',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 40,
    defaultHorizonMonths: 36,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'leasing-attrezzature',
    label: 'Leasing attrezzature',
    hint: 'Canoni leasing macchinari, attrezzature industriali, IT.',
    accountSuggestion: 'LEASING ATTREZZATURE',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 36,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'mutui',
    label: 'Mutui',
    hint: 'Rata mutuo (quota capitale + interessi). Senza IVA.',
    accountSuggestion: 'MUTUO',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 0,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 0,
    defaultHorizonMonths: 60,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'assicurazioni',
    label: 'Assicurazioni',
    hint: 'Premi assicurativi (RC, infortuni, fabbricato). Tipicamente annuali o semestrali, senza IVA.',
    accountSuggestion: 'ASSICURAZIONI',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'annual',
    defaultVatRate: 0,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 0,
    defaultHorizonMonths: 24,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'stipendi',
    label: 'Stipendi',
    hint: 'Netto in busta dei dipendenti. Aggiungi una riga per dipendente o un totale aggregato.',
    accountSuggestion: 'STIPENDI',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 0,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 0,
    defaultHorizonMonths: 24,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'contributi-inps-inail',
    label: 'Contributi INPS / INAIL',
    hint: 'Versamenti contributivi periodici (F24).',
    accountSuggestion: 'CONTRIBUTI INPS',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 0,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 0,
    defaultHorizonMonths: 24,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'acquisto-merci',
    label: 'Acquisto merci / materie prime',
    hint: 'Per commercio, manifattura, ristorazione: beni rivenduti o trasformati.',
    accountSuggestion: 'ACQUISTO MERCI',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 12,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'carburante-pedaggi',
    label: 'Carburante e pedaggi',
    hint: 'Rifornimenti, autostrade, ZTL. Deducibilità IVA tipica al 40% per auto aziendali.',
    accountSuggestion: 'CARBURANTE',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 40,
    defaultHorizonMonths: 12,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'manutenzioni',
    label: 'Manutenzioni e riparazioni',
    hint: 'Manutenzioni ordinarie/straordinarie su immobili, mezzi, attrezzature.',
    accountSuggestion: 'MANUTENZIONI',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'quarterly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 12,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'marketing-pubblicita',
    label: 'Marketing e pubblicità',
    hint: 'Google Ads, Meta Ads, agenzie marketing, materiale promozionale.',
    accountSuggestion: 'MARKETING',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 12,
    defaultStage: '0',
    defaultEnabled: true,
  },
  {
    id: 'cancelleria-ufficio',
    label: 'Cancelleria e materiali ufficio',
    hint: 'Carta, toner, articoli di consumo per l’ufficio.',
    accountSuggestion: 'CANCELLERIA',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'quarterly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 12,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'pulizie',
    label: 'Pulizie e igiene locali',
    hint: 'Servizi di pulizia di uffici, negozi, magazzini.',
    accountSuggestion: 'PULIZIE',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'monthly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 12,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'spese-bancarie',
    label: 'Spese e commissioni bancarie',
    hint: 'Canone conto, commissioni, bolli, spese POS. Senza IVA.',
    accountSuggestion: 'SPESE BANCARIE',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'quarterly',
    defaultVatRate: 0,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 0,
    defaultHorizonMonths: 12,
    defaultStage: '0',
    defaultEnabled: true,
  },
  {
    id: 'tributi-locali',
    label: 'Tributi locali (IMU / TARI)',
    hint: 'Tasse comunali su immobili e rifiuti. Annuali o semestrali, senza IVA.',
    accountSuggestion: 'TRIBUTI LOCALI',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'annual',
    defaultVatRate: 0,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 0,
    defaultHorizonMonths: 24,
    defaultStage: '0',
    defaultEnabled: false,
  },
  {
    id: 'formazione',
    label: 'Formazione e aggiornamento',
    hint: 'Corsi del personale, abbonamenti professionali, certificazioni.',
    accountSuggestion: 'FORMAZIONE',
    type: 'COSTO',
    sign: 'out',
    defaultArea: 'budget',
    defaultCadence: 'quarterly',
    defaultVatRate: 22,
    defaultWithholdingRate: 0,
    defaultVatDeduction: 100,
    defaultHorizonMonths: 12,
    defaultStage: '0',
    defaultEnabled: false,
  },
]

